### PR TITLE
Add fish completion script

### PR DESCRIPTION
**Pull request by dwhinham**
render1628813094927

### CODE REVIEW

**Comment by gmcn42** [comment]
Haha, from what I see in your animation `fish` definitely wins in the eye-candy department! Thanks for the script!

Now that we're at it, I decided to try a `zsh`-specific script as well, works fine:

zsh_completion-opt
zsh_completion

It has also a description feature like `fish`. Comparing the scripts though, I think the `fish` built-ins are way more elegant and readable.

Regarding the PR: How about having a directory `linux_src/completion_scripts` with `mt32-pi-ctl.{bash|zsh|fish}` inside?
I also want to move the installation instructions away from the option descriptions in README.md

If that's alright with you, I'll just push the changes to this branch and merge everything when it's done. :+1:

**Comment by dwhinham** [comment]
Excellent! I did wonderif zsh was the next step :)

Yes - one directory for all the scripts does make a lot of sense. Feel free to add whatever you like or change things as you see fit! 😀

**Comment by gmcn42** [comment]
All done! Made a 1.0.1a release containing the new scripts.

**Comment by dwhinham** [comment]
Great work!

I've updated the AUR package for Arch and all scripts are now installed to their respective locations. :slightly_smiling_face:

**Comment by gmcn42** [comment]
> I've updated the AUR package for Arch and all scripts are now installed to their respective locations.
Small observation regarding the PKGBUILD: Not sure if it's applicable to Arch but on Ubuntu the correct non-`/usr/local`-path  for third-party zsh-completions seems to be `/usr/share/zsh/vendor-completions`. The `zsh/site-functions` dir only exists in `fpath` for `/usr/local/share` prefix, not for `/usr/share`.

**Comment by dwhinham** [comment]
Yeah, I caught that - I just looked to see where other packages on my system were putting their function files and went with that (`/usr/share/zsh/site-functions`).

`/usr/local/share/zsh/site-functions` is in `fpath` and works, but using that location on Arch doesn't seem canonical.

**Pull request merged**
